pub mod guessing_game;
pub mod basic;
pub mod ownership;
pub mod references_borrowing;
pub mod slice_type;
pub mod structs;
pub mod struct_example;
pub mod enums_pattern_matching;
pub mod common_collections;
pub mod error_handling;
pub mod generic_type;
pub mod r#trait;
pub mod lifetimes;
mod closures_iterators;
mod smart_pointers;
mod thread;
